import images from '@/constants/image';

export const dummyCards = [
  {
    name: 'Jamal Agoro',
    location: 'Lagos, Nigeria',
    title: 'CTO AfriLaw',
    industry: 'Renewable Energy',
    rating: 4.8,
    imageSrc: `${images.man2}`,
    experience: '8 years',
    interest: 'Strategy & Finance',
    reviews: '20+ Reviews',
    baseLocation: 'Lagos',
    operatesIn: 'Nigeria, Ghana, Kenya',
    bio: 'Seasoned renewable energy executive with 8 years of experience building solar infrastructure across East and West Africa. Founded GreenEnergy Africa in 2018, scaling to $5M annual revenue by establishing distribution partnerships in 3 countries. Passionate about bridging Africa’s energy gap while delivering investor returns. Fluent in English and business-level French.',
    companyStage: 'Growth ($5M annual revenue)',
    keyStrength: 'East Africa distribution networks',
    topGoal: 'Seeking $3M Series A investors ($3M target) to expand off-grid solar solutions in secondary African cities.',
    brnMemberSince: 'January, 2025',
    responseRate: '92% (<6 hours avg.)',
    successfulDealsRate: '92% Dealings',
  },
  {
      name: 'Tunde Adebayo',
    location: 'Abuja, Nigeria',
    title: 'CEO InnovateHub',
    industry: 'Technology',
    rating: 4.9,
    imageSrc: `${images.man3}`,
    experience: '12 years',
    interest: 'AI & Machine Learning',
    reviews: '50+ Reviews',
    baseLocation: 'Abuja',
    operatesIn: 'Nigeria, UK, USA',
    bio: 'Aisha is a visionary leader in the Nigerian tech ecosystem. She specializes in leveraging AI to optimize business processes and create scalable software solutions. Her company, InnovateHub, has successfully launched several products for the local and international markets.',
    companyStage: 'Series B ($15M annual revenue)',
    keyStrength: 'AI product development & team management',
    topGoal: 'Expanding our AI-driven financial tools to new markets and securing strategic partnerships.',
    brnMemberSince: 'February, 2025',
    responseRate: '95% (<4 hours avg.)',
    successfulDealsRate: '98% Dealings',
  },
  {
    name: 'Adeola Adebayo',
    location: 'Port Harcourt, Nigeria',
    title: 'Founder, EcoBuild',
    industry: 'Real Estate',
    rating: 4.7,
    imageSrc: `${images.man4}`,
    experience: '15 years',
    interest: 'Sustainable Development',
    reviews: '35+ Reviews',
    baseLocation: 'Port Harcourt',
    operatesIn: 'Nigeria, Cameroon',
    bio: 'Tunde is an expert in sustainable real estate development, with a focus on affordable and eco-friendly housing projects. His firm, EcoBuild, is dedicated to solving Nigeria’s housing deficit with innovative, green solutions. He has extensive experience in project financing and local government relations.',
    companyStage: 'Startup ($2M annual revenue)',
    keyStrength: 'Sustainable building practices & project financing',
    topGoal: 'Acquiring land for our next major housing project and securing a $5M development loan.',
    brnMemberSince: 'March, 2025',
    responseRate: '88% (<12 hours avg.)',
    successfulDealsRate: '85% Dealings',
  },
  {
    name: 'Chioma Nwachukwu',
    location: 'Lagos, Nigeria',
    title: 'Venture Partner, NaijaVC',
    industry: 'Venture Capital',
    rating: 4.9,
    imageSrc: `${images.man2}`,
    experience: '10 years',
    interest: 'Fintech, Healthtech',
    reviews: '60+ Reviews',
    baseLocation: 'Lagos',
    operatesIn: 'West Africa',
    bio: 'Chioma is a seasoned venture capitalist with a strong track record of identifying and scaling high-potential startups. She focuses on early-stage investments in the fintech and healthtech sectors. Her expertise lies in due diligence, deal structuring, and providing strategic guidance to founders.',
    companyStage: 'Seed/Early Stage',
    keyStrength: 'Strategic investments & startup mentorship',
    topGoal: 'Sourcing the next generation of African unicorns and building a portfolio of impactful companies.',
    brnMemberSince: 'January, 2025',
    responseRate: '98% (<2 hours avg.)',
    successfulDealsRate: '100% Dealings',
  },
  {
    name: 'Emeka Okafor',
    location: 'Owerri, Nigeria',
    title: 'Founder, AgroConnect',
    industry: 'Agriculture',
    rating: 4.5,
    imageSrc: `${images.man4}`,
    experience: '7 years',
    interest: 'Agri-Tech, Supply Chain',
    reviews: '15+ Reviews',
    baseLocation: 'Owerri',
    operatesIn: 'Nigeria',
    bio: 'Emeka is a passionate agri-tech entrepreneur revolutionizing the food supply chain in Nigeria. His platform, AgroConnect, links small-scale farmers directly to urban markets, reducing waste and increasing farmer income. He is an expert in logistics and agricultural economics.',
    companyStage: 'Startup ($500K annual revenue)',
    keyStrength: 'Supply chain optimization & rural market penetration',
    topGoal: 'Securing a grant to expand operations to two new states and onboarding 1,000 new farmers.',
    brnMemberSince: 'March, 2025',
    responseRate: '85% (<1 day avg.)',
    successfulDealsRate: '80% Dealings',
  },
  {
    name: 'Amina Sani',
    location: 'Kano, Nigeria',
    title: 'Managing Partner, Sani & Co.',
    industry: 'Legal Services',
    rating: 4.6,
    imageSrc: `${images.man3}`,
    experience: '20 years',
    interest: 'Corporate Law, M&A',
    reviews: '40+ Reviews',
    baseLocation: 'Kano',
    operatesIn: 'Nigeria',
    bio: 'Amina is a highly respected corporate lawyer with two decades of experience. As a managing partner, she advises on complex mergers and acquisitions, business registration, and compliance. She is a key consultant for international firms looking to establish a presence in Northern Nigeria.',
    companyStage: 'Established Firm',
    keyStrength: 'Corporate law & regulatory compliance',
    topGoal: 'Expanding our client base with international companies and advising on major M&A deals in the tech sector.',
    brnMemberSince: 'February, 2025',
    responseRate: '90% (<8 hours avg.)',
    successfulDealsRate: '95% Dealings',
  },
  {
    name: 'Obinna Eze',
    location: 'Lagos, Nigeria',
    title: 'Marketing Director, Digify',
    industry: 'Digital Marketing',
    rating: 4.7,
    imageSrc: `${images.man4}`,
    experience: '9 years',
    interest: 'SEO, Content Strategy',
    reviews: '25+ Reviews',
    baseLocation: 'Lagos',
    operatesIn: 'Nigeria, South Africa',
    bio: 'Obinna is a growth-oriented marketing professional who has helped numerous Nigerian startups achieve significant user acquisition. His firm, Digify, specializes in data-driven SEO and content marketing strategies that deliver measurable results. He is skilled in digital analytics and performance marketing.',
    companyStage: 'Growth ($3M annual revenue)',
    keyStrength: 'Data-driven marketing & SEO strategy',
    topGoal: 'Helping new businesses optimize their digital presence and grow their online leads by 50% in 12 months.',
    brnMemberSince: 'April, 2025',
    responseRate: '93% (<5 hours avg.)',
    successfulDealsRate: '90% Dealings',
  },
  {
    name: 'Ifeoma Chukwu',
    location: 'Enugu, Nigeria',
    title: 'Founder, HealthTrack',
    industry: 'Healthtech',
    rating: 4.8,
    imageSrc: `${images.man4}`,
    experience: '6 years',
    interest: 'Telemedicine, EMR systems',
    reviews: '18+ Reviews',
    baseLocation: 'Enugu',
    operatesIn: 'Nigeria',
    bio: 'Ifeoma founded HealthTrack to improve access to healthcare in rural communities through telemedicine. Her platform connects patients with doctors and provides a secure way to manage medical records. She is a trained healthcare professional with a passion for tech solutions.',
    companyStage: 'Pre-Seed',
    keyStrength: 'Telemedicine solutions & clinical expertise',
    topGoal: 'Raising a seed round to expand our pilot program to two new states and partner with local clinics.',
    brnMemberSince: 'January, 2025',
    responseRate: '90% (<6 hours avg.)',
    successfulDealsRate: '88% Dealings',
  },
  {
    name: 'Ken Okoro',
    location: 'Lagos, Nigeria',
    title: 'Investment Analyst, CardinalStone',
    industry: 'Financial Services',
    rating: 4.7,
    imageSrc: `${images.man2}`,
    experience: '5 years',
    interest: 'Portfolio Management',
    reviews: '22+ Reviews',
    baseLocation: 'Lagos',
    operatesIn: 'Nigeria, UK',
    bio: 'Ken is a financial expert specializing in portfolio management and investment advisory. He works with high-net-worth individuals and corporate clients to build diversified investment portfolios. His insights into the Nigerian stock market and alternative investments are highly sought after.',
    companyStage: 'Established Firm',
    keyStrength: 'Investment analysis & portfolio diversification',
    topGoal: 'Advising clients on strategic investments in the Nigerian economy and growing our firm’s asset under management.',
    brnMemberSince: 'February, 2025',
    responseRate: '95% (<3 hours avg.)',
    successfulDealsRate: '94% Dealings',
  },
  {
    name: 'Grace Akinwumi',
    location: 'Ibadan, Nigeria',
    title: 'Founder, KidCoders',
    industry: 'Education',
    rating: 4.9,
    imageSrc: `${images.man1}`,
    experience: '10 years',
    interest: 'Edtech, Child Education',
    reviews: '55+ Reviews',
    baseLocation: 'Ibadan',
    operatesIn: 'Nigeria',
    bio: 'Grace is a pioneer in the EdTech space, leading a movement to teach coding and digital literacy to children in Nigeria. Her platform, KidCoders, provides engaging online and in-person courses. She is an advocate for early-age tech education and has partnered with several schools across the country.',
    companyStage: 'Growth ($1.5M annual revenue)',
    keyStrength: 'Curriculum development & educational technology',
    topGoal: 'Securing partnerships with public school systems and expanding our platform to reach 10,000 students.',
    brnMemberSince: 'March, 2025',
    responseRate: '96% (<4 hours avg.)',
    successfulDealsRate: '97% Dealings',
  },
];


   export const dummyLeads = [
        {
            name: 'Thabo Ladi',
            email: 'Username@gmail.com',
            title: 'COO EasyAccount',

            rating: 4.6,
            iconSrc: `${images.userCheck}`,
        },
        {
            name: 'P23 Africa',
            email: 'P23africa.com',
            title: 'Business & tech',

            rating: 4.6,
            iconSrc: `${images.userCheck}`,
        },
        {
            name: 'Kwame Nkrumah',
            email: 'kwame.n@example.com',
            title: 'CEO',
            rating: 4.6,
            iconSrc: `${images.userCheck}`,
        },
        {
            name: 'M-Pesa Holdings',
            email: 'contact@mpesa.com',
            title: 'Fintech',
            rating: 4.6,
            iconSrc: `${images.userCheck}`,
        },
        {
            name: 'Lola Adeoye',
            email: 'lola.a@example.com',
            title: 'CTO',
            rating: 4.6,
            iconSrc: `${images.userCheck}`,
        },
    ];
